FROM ubuntu:18.04

#계정
RUN useradd --create-home --shell /bin/bash hi && echo 'hi':'hi' | chpasswd
RUN echo 'root':'root' | chpasswd
# 저장소 변경
RUN sed -i "s/archive.ubuntu.com/mirror.kakao.com/g" /etc/apt/sources.list && sed -i "s/security.ubuntu.com/mirror.kakao.com/g" /etc/apt/sources.list
RUN apt-get update -y -qq
# 기본적인 설치
RUN apt-get install -y -qq curl
RUN apt-get install -y -qq net-tools
RUN apt-get install -y iproute2
# ssh 설치
# RUN apt-get install -y -qq openssh-server
# vim 설치
ADD https://raw.githubusercontent.com/dbwodlf3/mine-docker-file/master/llvm/.vimrc /root

# RUN apt-get install -y -qq vim
RUN curl -fLo /root/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 

#동기화 문제를 sleep으로 해결해버림. 나중에 추가할 필요가 있음.
RUN /bin/sh -c "vim -E -s -u '/root/.vimrc' +PlugInstall +qall & > /dev/null && sleep 30"

#빌드 툴 설치
RUN apt-get install gcc-8 -y
RUN apt-get install build-essential -y
RUN apt-get install cmake ninja-build -y
RUN apt-get install git -y

EXPOSE 22
