FROM ubuntu:18.04

ENV DEBIAN_FRONTEND='noninteractive'

# 저장소 업데이트
RUN sed -i "s/archive.ubuntu.com/mirror.kakao.com/g" /etc/apt/sources.list && \
    sed -i "s/security.ubuntu.com/mirror.kakao.com/g" /etc/apt/sources.list && \
    apt-get update

# 기본적인 설치
RUN apt-get install -yq --no-install-recommends \
    apt-utils \
    curl \
    net-tools \
    iproute2 \
    git

# php 설치
RUN apt-get install -yq --no-install-recommends \
    php-cli \
    php-fpm \ 
    php-json \
    php-xml \
    php.soap \
    php-curl \
    php-gd \
    php-ldap \
    php-mbstring \
    php-zip \
    php-intl \
    php-mysql \
    mariadb-client

# nginx 설치
RUN apt-get install -yq --no-install-recommends \
    nginx-core \
    nginx-common
